const
  //Eigenes Login als Softwarehersteller notwendig, um die Schnittstelle nutzen zu koennen
  //Registrierung unter https://www.itek.de/services/open-connect
  SHKCONNECT_LOGIN = ''; eintragen
  SHKCONNECT_PWD   = ''; eintragen
  //Diese URL ist nur zu Demozwecken, in Produktumgebungen durch eine eigene URL ersetzen
  //Wir moechten nicht die Daten Ihrer Kunden auf unserem Server :)
  IDSCONNECT_HOOKURL = 'https://www.landrix.de/test/idsconnect.php';